### ISSUE TITLE
FFmpeg isn't running!

### ISSUE THREAD

**Issue by xtianpaiva** [home-assistant/hassio#319]
Trying to use camera (YI Home) component, but having problems to start ffmpeg on Hass.io v1.1 and HA v0.61.1

`ffmpeg:

camera:
  - platform: yi
    name: 'Portón'
    host: '192.168.1.223'
    password: !secret yi_porton
    ffmpeg_arguments: '-vf scale=800:450'`

`WARNING (MainThread) [haffmpeg.core] FFmpeg isn't running!`

Is there something I'm missing?

**Comment by kjacksonmusic** [comment]
Same issue with yi camera. My Ring camera works fine for a while then Hassio will show this and neither works. Heres a thread with further details: 
https://www.reddit.com/r/homeassistant/comments/7rlq9x/anyone_using_ffmpeg_on_hassio/

**Comment by marcgarciamarti** [comment]
Hello, I do see the same statement in hassio logs. @xtianpaiva did you manage to solve this?

**Comment by pvizeli** [comment]
You need set it to debug and post the log to pvizeli/ha-ffmpeg

**Comment by marcgarciamarti** [comment]
Done: https://github.com/pvizeli/ha-ffmpeg/issues/22 

thanks @pvizeli

**Comment by fcollingwood** [comment]
Still an issue with 0.82:

> 2018-11-13 22:25:05 WARNING (MainThread) [haffmpeg.core] FFmpeg isn't running!

**Comment by dp106** [comment]
Still an issue on 0.83.3

**Comment by cmatte** [comment]
Still an issue with 0.84.6 on Docker / Synology NAS:
`2018-12-27 23:53:09 WARNING (MainThread) [haffmpeg.core] FFmpeg isn't running!`

**Comment by manuel-jrs** [comment]
Same on hassio 0.87.0

**Comment by PDekker** [comment]
Same here on 0.87

**Comment by diogoribeiro09** [comment]
Same here on 0.87.1
Has anyone figured out how to solve it ?

**Comment by jeffl78** [comment]
I'm having the same problem but I just got around to putting my cameras in hass.io/docker on raspi 3b stretch and can't seem to get them to show up.  I see them in developmer tools "states"  but they say idle.  I don't see any errors but haven't tried running the trouble shooting yet.

**Comment by alb147** [comment]
same in 0.88.2 with YI camera.

**Comment by diogoribeiro09** [comment]
Hi,

This configuration made it work for me.

> camera:
>   - platform: yi
>     name: Camera
>     host: 192.168.1.82
>     password: !secret domePass
>     path: /tmp/sd/record
>     ffmpeg_bin: /usr/local/bin/ffmpeg
>     ffmpeg_arguments: '-vf scale=800:450'

Hope it solves the problem for anyone else :)

**Comment by alb147** [comment]
> 
> 
> Hi,
> 
> This configuration made it work for me.
> 
> > camera:
> > 
> > * platform: yi
> >   name: Camera
> >   host: 192.168.1.82
> >   password: !secret domePass
> >   path: /tmp/sd/record
> >   ffmpeg_bin: /usr/local/bin/ffmpeg
> >   ffmpeg_arguments: '-vf scale=800:450'
> 
> Hope it solves the problem for anyone else :)
> 
> EDIT: The path for the camera footage was identified by using ftp to access the camera and finding where it was being stored. It may be subjected to change on your particular camera. My camera is the 'Yi Dome'.

what it´s yous HA version?
i have a  0.88.2 and don´t running. :(

**Comment by jeffl78** [comment]
I just saw this, did you use ftp as a search term, or how did you determine the ftp file path? Will it run without the record path initially?  I think the answer is yes, it being an optional parameter.

**Comment by adantoft** [comment]
Take a look here: https://community.home-assistant.io/t/ffmpeg-isnt-running-problem/96172

I was able to get mine working by following the _exact same_ config - apparently the docker version of home assistant is much more picky on how it's configured.

**Comment by jeffl78** [comment]
I have them loaded without error on a clean install, but they're state is idle and it they still won't show up in the frontend.  I'm playing around with the options to see what works.
