### ISSUE TITLE
"hassio ho hardware" command returns "Error decoding json invalid character ':' after top-level value: 404: Not Found"

### ISSUE THREAD

**Issue by sveip** [home-assistant/hassio#443]
Typing `hassio ho hardware`
returns: `Error decoding json invalid character ':' after top-level value: 404: Not Found`

Versions:
Supervisor:
Version | 0.101
Channel | beta

Home Assistant
0.67.0b1

**Comment by pvizeli** [comment]
Yes, we need update the cli @ryanm101

**Comment by ryanm101** [comment]
Fixed by https://github.com/home-assistant/hassio-cli/pull/73

**Comment by Burnett2k** [comment]
I'm now getting this issue and am unsure how to resolve it. I've upgraded to hassio 70.0, but I'm not sure how to check version of the CLI or upgrade it.

**Comment by ryanm101** [comment]
@Burnett2k hassio --version
you may need to update the ssh addon

**Comment by Burnett2k** [comment]
I'm currently at 1.2.1

I just ran `hassio ad update --name core_ssh` which updated my SSH addon from v3.4 to v3.6 . When I try to run most commands I still get an error.

Also, even when I completely reboot my machine it still gets in this bad state where I cannot even access the web interface at all. It has been down for about 3 days now.
```
core-ssh:~# **hassio -d ha restart**
DEBUG [CmdHomeassistant]: action->'restart', endpoint='restart', serverOverride->'', GET->'false', options->'', rawjson->'false', filter->''
DEBUG [ExecCommand]: basepath->'homeassistant', endpoint->'restart', serverOverride->'', get->'false', Options->'', Filter->'', RawJSON->'false'
DEBUG [GenerateURI]: basepath->'homeassistant', endpoint->'restart', serverOverride->''
DEBUG [RestCall]: data->'http://hassio/homeassistant/restart', GET->'false', payload->''
DEBUG [RestCall]: ResponseBody->'{"result": "error", "message": null}'
ERROR
panic: interface conversion: interface is nil, not string
goroutine 1 [running]:
panic(0x2c7050, 0x1070b720)
        /home/travis/.gimme/versions/go1.7.6.linux.amd64/src/runtime/panic.go:500 +0x33c
github.com/home-assistant/hassio-cli/command/helpers.DisplayOutput(0x107b6200, 0x24, 0x200, 0x0)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:118 +0x3c8
github.com/home-assistant/hassio-cli/command/helpers.ExecCommand(0x2f6f83, 0xd, 0x7eb05e61, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:155 +0x308
github.com/home-assistant/hassio-cli/command.CmdHomeassistant(0x10778420)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/homeassistant.go:48 +0x540
github.com/urfave/cli.HandleAction(0x2af768, 0x324b14, 0x10778420, 0x0, 0x0)
        /home/travis/gopath/src/github.com/urfave/cli/app.go:503 +0xf0
github.com/urfave/cli.Command.Run(0x2f6f83, 0xd, 0x0, 0x0, 0x40bd10, 0x1, 0x1, 0x301e4d, 0x2f, 0x0, ...)
        /home/travis/gopath/src/github.com/urfave/cli/command.go:165 +0x6b8
github.com/urfave/cli.(*App).Run(0x107648c0, 0x1070a160, 0x4, 0x4, 0x0, 0x0)
        /home/travis/gopath/src/github.com/urfave/cli/app.go:259 +0x8b0
main.main()
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/main.go:22 +0x108
```

```core-ssh:~# **hassio su logs**
Error decoding json invalid character '\x1b' looking for beginning of value: 18-06-02 09:53:24 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 09:53:36 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 09:53:36 INFO (SyncWorker_12) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 09:53:38 INFO (SyncWorker_12) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 10:03:39 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 10:03:52 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 10:03:52 INFO (SyncWorker_14) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 10:03:53 INFO (SyncWorker_14) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 10:04:12 INFO (MainThread) [hassio.snapshots] Found 1 snapshot files
18-06-02 10:04:12 INFO (MainThread) [hassio.host.info] Update local host information
18-06-02 10:04:12 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
18-06-02 10:13:54 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 10:14:07 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 10:14:07 INFO (SyncWorker_4) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 10:14:09 INFO (SyncWorker_4) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 10:24:09 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 10:24:13 ERROR (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant API!
18-06-02 10:24:13 INFO (SyncWorker_10) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 10:24:15 INFO (SyncWorker_6) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 10:34:16 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 10:34:22 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 10:34:22 INFO (SyncWorker_1) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 10:34:25 INFO (SyncWorker_1) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 10:44:26 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 10:44:37 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 10:44:37 INFO (SyncWorker_15) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 10:44:39 INFO (SyncWorker_15) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 10:54:40 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 10:54:53 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 10:54:53 INFO (SyncWorker_4) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 10:54:55 INFO (SyncWorker_4) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 11:04:55 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 11:05:08 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 11:05:08 INFO (SyncWorker_6) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 11:05:10 INFO (SyncWorker_6) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 11:15:10 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 11:15:23 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 11:15:23 INFO (SyncWorker_1) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 11:15:25 INFO (SyncWorker_1) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 11:25:26 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 11:25:38 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 11:25:38 INFO (SyncWorker_15) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 11:25:40 INFO (SyncWorker_15) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 11:35:41 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 11:35:53 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 11:35:53 INFO (SyncWorker_4) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 11:35:55 INFO (SyncWorker_4) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 11:45:56 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 11:46:09 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 11:46:09 INFO (SyncWorker_6) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 11:46:10 INFO (SyncWorker_6) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 11:56:11 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 11:56:24 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 11:56:24 INFO (SyncWorker_1) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 11:56:26 INFO (SyncWorker_1) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 12:06:26 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 12:06:39 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 12:06:39 INFO (SyncWorker_15) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 12:06:42 INFO (SyncWorker_15) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 12:16:42 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 12:16:54 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 12:16:54 INFO (SyncWorker_4) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 12:16:56 INFO (SyncWorker_4) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 12:26:57 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 12:27:10 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 12:27:10 INFO (SyncWorker_6) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 12:27:12 INFO (SyncWorker_6) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 12:37:12 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 12:37:25 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 12:37:25 INFO (SyncWorker_1) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 12:37:28 INFO (SyncWorker_1) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 12:47:29 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 12:47:40 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 12:47:40 INFO (SyncWorker_15) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 12:47:42 INFO (SyncWorker_15) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 12:57:42 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 12:57:55 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 12:57:55 INFO (SyncWorker_4) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 12:57:57 INFO (SyncWorker_4) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 13:07:57 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-06-02 13:08:10 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-06-02 13:08:10 INFO (SyncWorker_6) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-06-02 13:08:12 INFO (SyncWorker_6) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.70.0
18-06-02 13:09:28 INFO (MainThread) [hassio.api.security] /addons access from core_ssh
18-06-02 13:09:41 INFO (MainThread) [hassio.api.security] /addons/ssh_server/info access from core_ssh
18-06-02 13:11:58 INFO (MainThread) [hassio.api.security] /addons/core_ssh/info access from core_ssh
18-06-02 13:12:14 INFO (MainThread) [hassio.api.security] /addons/core_ssh/update access from core_ssh
18-06-02 13:12:14 INFO (SyncWorker_1) [hassio.docker.interface] Update docker 3.4 with homeassistant/armhf-addon-ssh:3.6
18-06-02 13:12:14 INFO (SyncWorker_1) [hassio.docker.interface] Pull image homeassistant/armhf-addon-ssh tag 3.6.
18-06-02 13:12:44 INFO (SyncWorker_1) [hassio.docker.interface] Tag image homeassistant/armhf-addon-ssh with version 3.6 as latest
18-06-02 13:12:44 INFO (SyncWorker_1) [hassio.docker.interface] Stop homeassistant/armhf-addon-ssh docker application
18-06-02 13:12:45 INFO (SyncWorker_1) [hassio.docker.interface] Clean homeassistant/armhf-addon-ssh docker application
18-06-02 13:12:45 INFO (SyncWorker_1) [hassio.docker.interface] Cleanup docker images: ['homeassistant/armhf-addon-ssh:3.4']
18-06-02 13:12:49 INFO (SyncWorker_16) [hassio.docker.addon] Start docker addon homeassistant/armhf-addon-ssh with version 3.6
18-06-02 13:13:42 INFO (MainThread) [hassio.api.security] /addons/core_ssh/info access from core_ssh
18-06-02 13:13:54 INFO (MainThread) [hassio.api.security] /homeassistant/restart access from core_ssh
18-06-02 13:13:54 ERROR (MainThread) [hassio.utils] Can't excute restart while a task is in progress
18-06-02 13:15:20 INFO (MainThread) [hassio.api.security] /homeassistant/restart access from core_ssh
18-06-02 13:15:20 ERROR (MainThread) [hassio.utils] Can't excute restart while a task is in progress
18-06-02 13:16:07 INFO (MainThread) [hassio.api.security] /supervisor/logs access from core_ssh
```

Unfortunately, my last snapshot is from ~6 months ago, but I do have all my configs stored in git so I'm thinking the best thing to do may be to just revert to the snapshot and get a new build of Hassio running?  Unfortunately, the logs don't seem to be giving any good indication of the problem.
