### ISSUE TITLE
Home Assistant stuck on udevd[10]: Starting eudev-3.2.5

### ISSUE THREAD

**Issue by imcoltanmay** [home-assistant/hassio#859]
**Home Assistant release with the issue:**
HassOs 2.3

**Home Assistant release with the issue:**
1.4.0

**Operating environment (HassOS/Generic):**

**Supervisor logs:**

**Description of problem:**
Home Assistant stuck on udevd[10]: Starting eudev-3.2.5

**Comment by sadsadie** [comment]
The same was happening to me for days... If you have a chromecast or google home in the network try to disconnect it and restart hassio.

**Comment by pvizeli** [comment]
Yeah, ChromeCast can lock your startup. We need to fix that

**Comment by tobynz** [comment]
Same problem here. RPi 3 B+, fresh install, nothing but ethernet, hdmi and power plugged in. No chromecast on network.

**Comment by rudgr** [comment]
Seem to be having the Same issue

**Comment by pondguy1115** [comment]
I 'had' the same issue. RP1 3 B+, ethernet, HDMI, power, and unplugged my Chromecast. Must have installed it 10 times, not an exaggeration. Wrote down what I configured, installed, rebooted, etc. EVERY time I installed weather, either DarkSky or Openweather, it would hang on EUDEV. This time I installed SSH. Added weather, rebooted, it was hung at EUDEV. I SSHed in, edited the Configuration.yaml, took out the weather, rebooted, it's working!

**Comment by btoorenburg** [comment]
Same issue here. There is no Chromecast in my network.

**Comment by obiraa** [comment]
Same here. Unplugged Google Homes and Chromecasts and still stuck.

**Comment by cogneato** [comment]
@pondguy1115 
![image](https://user-images.githubusercontent.com/2456810/52217728-49162f80-2856-11e9-9c54-89a8090ff0b0.png)
This is normal to see. A configuration error can prevent your UI from loading. You may have been adding the weather component incorrectly?

**Comment by btoorenburg** [comment]
I haven't been adding anything. 

Just the normal installation. 




 Van:   cogneato <notifications@github.com> 
 Aan:   home-assistant/hassio <hassio@noreply.github.com> 
 Cc:   Bas Toorenburg <toorenburgsj@timbv.nl>, Comment <comment@noreply.github.com> 
 Verzonden:   4-2-2019 16:25 
 Onderwerp:   Re: [home-assistant/hassio] Home Assistant stuck on udevd[10]: Starting eudev-3.2.5 (#859) 


@pondguy1115
 
 This is normal to see. A configuration error can prevent your UI from loading. You may have been adding the weather component incorrectly? 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread. 

Met vriendelijke groet, 
Bas Toorenburg



www.timbv.nl
toorenburgsj@timbv.nl

Drs. ing. SJ Toorenburg
De Kwartel 5
8251 MS DRONTEN
Telefoonnr    +31 321 382 816
Mobiel    + 31 6 270 703 15

  http://twitter.com/#!/bastoorenburg

 http://nl.linkedin.com/pub/bas-toorenburg/a/60/243

E-mail disclaimer:
_______________________________________________________________________________________________________

Dit e-mailbericht en enige bijlage is uitsluitend bestemd voor de geadresseerde(n) en strikt vertrouwelijk of anderszins wettelijk beschermd. In dit bericht vervatte opvattingen of meningen zijn uitsluitend die van de schrijver en niet per definitie die van TIM Bedrijfskundig Advies. Als dit bericht niet voor u bestemd is, wordt u vriendelijk verzocht dit aan de afzender te melden. Alleen de geadresseerde mag de informatie gebruiken. Het is niet toegestaan om de informatie openbaar te maken, te vermenigvuldigen, te verspreiden of te verstrekken aan derden.

TIM Bedrijfskundig Advies spant zich ervoor in dat u juiste, volledige en tijdige informatie ontvangt.
TIM Bedrijfskundig Advies kan op geen enkele wijze verantwoordelijk of aansprakelijk worden gehouden voor en/of in verband met de gevolgen van en/of schade ontstaan door het onjuist, onvolledig en/of niet-tijdig versturen en ontvangen van de inhoud van dit bericht. TIM Bedrijfskundig Advies is niet aansprakelijk voor virussen in dit e-mailbericht en/of enige bijlage.

Voor informatie over TIM Bedrijfskundig Advies raadpleegt u www.timbv.nl
_______________________________________________________________________________________________________

**Comment by phienan** [comment]
Hi everyone,
I'm doing a fresh installation for the first time.  I had disconnected existing Iris, Alexa, Chromecast and Firesticks from my network.  HassOs is running on Raspberry pi 2B+ and it got stuck at boot time.  Error message is the same as everyone having here, starting eudev-3.2.5.

Kindly appreciate if anyone sharing some leads.

Thank you

**Comment by xerxel** [comment]
I just spent half an hour configuring this and now the first time I come to reboot, it hangs! All I did was follow instructions in the video... :-(

**Comment by pondguy1115** [comment]
I did not install every one, but with the latest batch of updates, it no longer hangs. Weather was configured the same now as it was when hanging. Whatever my issue was, it was fixed in the updates.

**Comment by robhuls** [comment]
Same message here (eudev-3.2.7) with a brand new install, just the image 
https://github.com/home-assistant/hassos/releases/download/2.10/hassos_rpi3-2.10.img.gz. no configuration at all. I disconnected my chromecast, still the same. I really start to long for a stable branch, my hassio instance constantly breaking for months now.

**Comment by gdreelin** [comment]
I have had the exact same thing but hangs on udevd[8]: starting eudev-3.2.7 after 8 tried to get this built on a RaspPi 3 B+. I am updated to 89 version.

**Comment by dheath73** [comment]
Exactly the same for me as well, hangs on udevd[8]: starting eudev-3.2.7 - running 0.89

**Comment by JuliusLedoux** [comment]
Same here running on a vmware environment. Stuck exactly at the same place. I removed all the sensors and forced a reboot, still does not work. The really interesting thing is that NodeRed, mosquitto, SAMBA still work (added them via addons) and they are (obviously) on the same box and IP Addresss.

**Comment by averagecanadian** [comment]
So not sure if anyone else is as dumb as I am but I was 'stuck' in the same spot when trying to set this up in a vm environment. Not sure why I expected my VM to have a gui but that's what I was waiting for... Moved over to my desktop and realized it was waiting for me to complete the setup in my browser.

**Comment by pvizeli** [comment]
You will never see more as `udevd[8]: starting eudev-3.2.7`. That means Home Assistant is starting up.

If you want see logs, try `hassio ha logs`

**Comment by uglurass** [comment]
same here. seems it stops at the configuration . yaml now i wish i could just enter command -del config/configuration.yaml. or open nano configuration.yaml and edit it.

**Comment by cestfauxcestfaux** [comment]
Same error here :(
It was working yesterday, today it is stucked there.
The only different thing I done was to place my Tinker Box in a case... and plugged a cooler fan... but it shouldn't have had any impact on it.... :(
